version: "3.8"

services:
  web:
    build: .
    command: sh -c "uvicorn app:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
